djangoapp/blog/urls.py
from django.urls import path
from blog.views import PostListView, PostDetailView, PageDetailView,\
    CreatedByListView, CategoryListView, TagListView, SearchListView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='index'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post'),
    path('page/<slug:slug>/', PageDetailView.as_view(), name='page'),
    path('created_by/<int:author_pk>/',
         CreatedByListView.as_view(), name='created_by'
         ),
    path('category/<slug:slug>/', CategoryListView.as_view(), name='category'),
    path('tag/<slug:slug>/', TagListView.as_view(), name='tag'),
    path('search/', SearchListView.as_view(), name='search'),
]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangoapp/blog/models.py
from django.db import models
from utils.rands import slugify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django_summernote.models import AbstractAttachment
from django.urls import reverse


class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name

        current_file_name = str(self.file.name)
        super_save = super().save(*args, **kwargs)
        file_changed = False

        if self.file:
            file_changed = current_file_name != self.file.name

        if file_changed:
            resize_image(self.file, 900, True, 70)

        return super_save


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 5)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.name, 5)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class PostManager(models.Manager):
    def get_published(self):
        return self.filter(is_published=True).order_by('-pk')


class Page(models.Model):
    objects = PostManager()

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255
    )
    is_published = models.BooleanField(
        default=False,
        help_text='Deixe Marcado Para Exibir Essa Página !'
        )
    content = models.TextField()

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:page', args=(self.slug,))

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 5)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Post(models.Model):
    objects = PostManager()

    title = models.CharField(max_length=65)
    slug = models.SlugField(
        unique=True, default=None,
        null=True, blank=True, max_length=255
    )
    excerpt = models.CharField(max_length=150)
    is_published = models.BooleanField(
        default=False,
        help_text='Deixe Marcado Para Exibir Esse Post !'
    )
    content = models.TextField()
    cover = models.ImageField(upload_to='posts/%Y/%m', blank=True, default='')
    cover_in_post_content = models.BooleanField(
        default=True,
        help_text='Deixe Marcado Para Exibir a Imagem da Capa Dentro do Post !'
    )
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='post_created_by'
        )
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='post_updated_by'
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True,
        default=None
        )
    tags = models.ManyToManyField(
        Tag, blank=True, default=''
    )

    def get_absolute_url(self):
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify_new(self.title, 5)

        current_cover_name = str(self.cover.name)
        super_save = super().save(*args, **kwargs)
        cover_changed = False

        if self.cover:
            cover_changed = current_cover_name != self.cover.name

        if cover_changed:
            resize_image(self.cover, 900, True, 70)

        return super_save

djangoapp/blog/views.py
from typing import Any
from django.shortcuts import redirect
from blog.models import Post, Page
from django.db.models import Q
from django.contrib.auth.models import User
from django.http import Http404
from django.views.generic import ListView, DetailView

PER_PAGE = 9


class PostListView(ListView):
    template_name = 'blog/pages/index.html'
    context_object_name = 'posts'
    paginate_by = PER_PAGE
    queryset = Post.objects.get_published()

    # def get_queryset(self): # one way to change queryset
    #     queryset = super().get_queryset()
    #     queryset = queryset.filter(is_published=True)
    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'title': 'Home |'
        })

        return context


class CreatedByListView(PostListView):
    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self._temp_context: dict[str, Any] = {}

    def get(self, request, *args, **kwargs):
        author_pk = self.kwargs.get('author_pk')
        user = User.objects.filter(pk=author_pk).first()

        if user is None:
            raise Http404()

        self._temp_context.update({
            'author_pk': author_pk,
            'user': user
        })

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self._temp_context['user']
        user_full_name = user.username

        if user.first_name:
            user_full_name = f'{user.first_name} {user.last_name}'

        context.update({
            'title': f'Posts de {user_full_name} |'
        })

        return context

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(created_by=self._temp_context['user'].pk)
        return qs


class CategoryListView(PostListView):
    allow_empty = False

    def get_queryset(self):
        return super().get_queryset().filter(
            category__slug=self.kwargs.get('slug')
            )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = f'{self.object_list[0].category.name} |'

        context.update({
            'title': page_title
        })

        return context


class TagListView(PostListView):
    allow_empty = False

    def get_queryset(self):
        return super().get_queryset().filter(
            tags__slug=self.kwargs.get('slug')
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = f'{self.object_list[0].tags.first().name} |'

        context.update({
            'title': page_title
        })

        return context


class PageDetailView(DetailView):
    model = Page
    template_name = 'blog/pages/page.html'
    slug_field = 'slug'
    context_object_name = 'page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.get_object()
        page_title = f'{page.title} |'

        context.update({
            'title': page_title
        })

        return context

    def get_queryset(self):
        return super().get_queryset().filter(
            is_published=True
        )


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/pages/post.html'
    slug_field = 'slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        page_title = f'{post.title} |'

        context.update({
            'title': page_title
        })

        return context

    def get_queryset(self):
        return super().get_queryset().filter(
            is_published=True
        )


class SearchListView(PostListView):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._search_value = ''

    def setup(self, request, *args, **kwargs):
        self._search_value = request.GET.get('search', '').strip()

        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        if self._search_value == '':
            return redirect('blog:index')

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        search_value = self._search_value

        return super().get_queryset().filter(
            Q(title__icontains=search_value) |
            Q(excerpt__icontains=search_value) |
            Q(content__icontains=search_value)
        )[0:PER_PAGE]

    def get_context_data(self, **kwargs):
        search_value = self._search_value
        context = super().get_context_data(**kwargs)

        context.update({
            'search_value': search_value,
            'title': f'{self._search_value[:10]} - Search |'
        })

        return context

djangoapp/blog/templates/blog/pages/index.html
{% extends 'blog/base.html' %} 

{% block content %}

<main class="main-content section-wrapper">
  <div class="section-content-wide">
    <div class="section-gap">

      {% if posts %}
        <div class="card-grid">
          {% for post in posts %} 
              {% include 'blog/partials/post-card.html'%} 
          {% endfor %}
        </div>
      
      {% else %}
        <div class="not-found center">
          <h1>Nada Encontrado 😞</h1>
          <p>
            Não Encontrei Nada Nessa Consulta. Clique em Outro Link ou Vá Para a 
            <a href="{% url 'blog:index' %}">Home</a>
          </p>
        </div>
      {% endif %}

    </div>
  </div>
</main>

{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
{% extends 'blog/base.html' %} 

{% block content %}

<main class="main-content section-wrapper">
  <div class="section-content-narrow">
    <div class="section-gap">
      <h1 class="center">{{ page.title }}</h1>
      <p>
        {{ page.content|safe }}
      </p>
    </div>
  </div>
</main>

{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
{% extends 'blog/base.html' %} 

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}

<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %}
        <div class="single-post-cover pb-base">
          <img loading="lazy" src="{{ post.cover.url }}" alt="Cover de {{ post.title }}"/>
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{ post.title }}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
          <a class="post-meta-link" href="{% url 'blog:created_by' post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>
            <span> 
              {% if post.created_by.first_name %}
                {{ post.created_by.first_name }} 
                {{ post.created_by.last_name }} 
              {% else %}
                {{ post.created_by.username }}
              {% endif %}
            </span>
          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span> {{ post.created_at|date:'d/m/Y \à\s H:i' }} </span>
          </span>
        </div>

        {% if post.category %}
          <div class="post-meta-item">
            <a class="post-meta-link" href="{% url 'blog:category' post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span> {{ post.category.name }} </span>
            </a>
          </div>
        </div>
      {% endif %}

      <p class="single-post-excerpt pb-base">
        {{ post.excerpt|safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        {{ post.content|safe }}

        {% if post.tags.all.exists %}
        <div class="post-tags">
          <span>Tags: </span>
          
            {% for tag in post.tags.all  %}
            <a class="post-tag-link" href="{% url 'blog:tag' tag.slug %}">
              <i class="fa-solid fa-link"></i>
              <span> {{ tag.name }} </span>
            </a>
            {% endfor %}
        </div>
        {% endif %}

      </div>
    </div>
  </div>
</main>

{% endblock content %}